### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by cedorman** [NextCenturyCorporation/AIDA-Interchange-Format#99]
The pull request #97 causes the ImagesToAIFTest.java test to fail.  The line is:  

require(baseUri.substring(1).contains(":")) {
     "Base URI must contain a prefix followed by a colon separator" }

and the output of the test is:

16:48:10.305 [main] INFO  mu.KLogging - Read header line as system URI www.isi.edu/testSystem

java.lang.IllegalArgumentException: Base URI must contain a prefix followed by a colon separator

	at edu.isi.gaia.UuidIriGenerator.<init>(AIFUtils.kt:726)
	at edu.isi.gaia.ImagesToAIF$Companion.createForSystemIri(imagesToAIF.kt:156)

I think that the problem is that the resources file that is being used in the test was not updated in accordance with the change in test.

**Comment by cedorman** [comment]
This was fixed and merged (branch AIF-99).
